name: Build and Deploy ASP.NET Core 8.0

on:
  push:
    branches:
      - main  # thay đổi nếu bạn dùng nhánh khác

jobs:
  build:
    #runs-on: windows-latest
    runs-on: ubuntu-latest
    
    steps:
      # 1. Lấy source code từ GitHub
      - name: Checkout source code
        uses: actions/checkout@v3

      # 2. Cài đặt .NET SDK 8.0
      - name: Setup .NET SDK
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'

      # 3. Khôi phục dependencies
      - name: Restore dependencies
        run: dotnet restore

      # 4. Build project
      - name: Build project
        run: dotnet build --configuration Release --no-restore

      # 5. Publish project
      - name: Publish project
        run: dotnet publish -c Release -o ./publish --no-build

      # 6. Deploy (sử dụng SCP để copy file lên server Windows)
      - name: Deploy to IIS server via SCP
        uses: appleboy/scp-action@v0.1.3
        with:
          host: 115.74.31.254
          username: administrator
          password: '123123'
          port: 22
          source: "./publish/"
          target: "C:/inetpub/MyApp"
